spring.application.name=pairly

spring.datasource.url=jdbc:mysql://localhost:3306/pairly_db
spring.datasource.username=amolm
spring.datasource.password=amol5941

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.thymeleaf.cache=false